// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: pkg/protocol/metrics.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_CPU_USAGE       MetricType = 0
	MetricType_MEMORY_USAGE    MetricType = 1
	MetricType_NETWORK_PACKETS MetricType = 2
	MetricType_EBPF_RAW        MetricType = 3
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "CPU_USAGE",
		1: "MEMORY_USAGE",
		2: "NETWORK_PACKETS",
		3: "EBPF_RAW",
	}
	MetricType_value = map[string]int32{
		"CPU_USAGE":       0,
		"MEMORY_USAGE":    1,
		"NETWORK_PACKETS": 2,
		"EBPF_RAW":        3,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_protocol_metrics_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_pkg_protocol_metrics_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Type          MetricType             `protobuf:"varint,5,opt,name=type,proto3,enum=protocol.MetricType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_CPU_USAGE
}

func (x *Metric) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsResponse) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type BatchMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetricsRequest) Reset() {
	*x = BatchMetricsRequest{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetricsRequest) ProtoMessage() {}

func (x *BatchMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetricsRequest.ProtoReflect.Descriptor instead.
func (*BatchMetricsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *BatchMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *BatchMetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BatchMetricsRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type BatchMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,3,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int32                  `protobuf:"varint,4,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMetricsResponse) Reset() {
	*x = BatchMetricsResponse{}
	mi := &file_pkg_protocol_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMetricsResponse) ProtoMessage() {}

func (x *BatchMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMetricsResponse.ProtoReflect.Descriptor instead.
func (*BatchMetricsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *BatchMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchMetricsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchMetricsResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *BatchMetricsResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

var File_pkg_protocol_metrics_proto protoreflect.FileDescriptor

const file_pkg_protocol_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/protocol/metrics.proto\x12\bprotocol\"\x85\x02\n" +
	"\x06Metric\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x124\n" +
	"\x06labels\x18\x04 \x03(\v2\x1c.protocol.Metric.LabelsEntryR\x06labels\x12(\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.protocol.MetricTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x0eMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"=\n" +
	"\x0fMetricsResponse\x12*\n" +
	"\ametrics\x18\x01 \x03(\v2\x10.protocol.MetricR\ametrics\"z\n" +
	"\x13BatchMetricsRequest\x12*\n" +
	"\ametrics\x18\x01 \x03(\v2\x10.protocol.MetricR\ametrics\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x98\x01\n" +
	"\x14BatchMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaccepted_count\x18\x03 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x04 \x01(\x05R\rrejectedCount*P\n" +
	"\n" +
	"MetricType\x12\r\n" +
	"\tCPU_USAGE\x10\x00\x12\x10\n" +
	"\fMEMORY_USAGE\x10\x01\x12\x13\n" +
	"\x0fNETWORK_PACKETS\x10\x02\x12\f\n" +
	"\bEBPF_RAW\x10\x032c\n" +
	"\x0eMetricsService\x12Q\n" +
	"\x10SendBatchMetrics\x12\x1d.protocol.BatchMetricsRequest\x1a\x1e.protocol.BatchMetricsResponseB+Z)github.com/konpure/Kon-Agent/pkg/protocolb\x06proto3"

var (
	file_pkg_protocol_metrics_proto_rawDescOnce sync.Once
	file_pkg_protocol_metrics_proto_rawDescData []byte
)

func file_pkg_protocol_metrics_proto_rawDescGZIP() []byte {
	file_pkg_protocol_metrics_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_metrics_proto_rawDesc), len(file_pkg_protocol_metrics_proto_rawDesc)))
	})
	return file_pkg_protocol_metrics_proto_rawDescData
}

var file_pkg_protocol_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_protocol_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_protocol_metrics_proto_goTypes = []any{
	(MetricType)(0),              // 0: protocol.MetricType
	(*Metric)(nil),               // 1: protocol.Metric
	(*MetricsRequest)(nil),       // 2: protocol.MetricsRequest
	(*MetricsResponse)(nil),      // 3: protocol.MetricsResponse
	(*BatchMetricsRequest)(nil),  // 4: protocol.BatchMetricsRequest
	(*BatchMetricsResponse)(nil), // 5: protocol.BatchMetricsResponse
	nil,                          // 6: protocol.Metric.LabelsEntry
}
var file_pkg_protocol_metrics_proto_depIdxs = []int32{
	6, // 0: protocol.Metric.labels:type_name -> protocol.Metric.LabelsEntry
	0, // 1: protocol.Metric.type:type_name -> protocol.MetricType
	1, // 2: protocol.MetricsResponse.metrics:type_name -> protocol.Metric
	1, // 3: protocol.BatchMetricsRequest.metrics:type_name -> protocol.Metric
	4, // 4: protocol.MetricsService.SendBatchMetrics:input_type -> protocol.BatchMetricsRequest
	5, // 5: protocol.MetricsService.SendBatchMetrics:output_type -> protocol.BatchMetricsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_protocol_metrics_proto_init() }
func file_pkg_protocol_metrics_proto_init() {
	if File_pkg_protocol_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_metrics_proto_rawDesc), len(file_pkg_protocol_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_metrics_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_metrics_proto_depIdxs,
		EnumInfos:         file_pkg_protocol_metrics_proto_enumTypes,
		MessageInfos:      file_pkg_protocol_metrics_proto_msgTypes,
	}.Build()
	File_pkg_protocol_metrics_proto = out.File
	file_pkg_protocol_metrics_proto_goTypes = nil
	file_pkg_protocol_metrics_proto_depIdxs = nil
}
